Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
April 05, 2023 - 13:15:36
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Error: That port is already in use.
[05/Apr/2023 13:17:00] "GET /polls HTTP/1.1" 301 0
[05/Apr/2023 13:18:04] "GET /polls HTTP/1.1" 301 0
[05/Apr/2023 13:18:06] "GET /polls HTTP/1.1" 301 0
[05/Apr/2023 13:18:23] "GET /polls/ HTTP/1.1" 200 40
[05/Apr/2023 13:30:31] "GET /polls/ HTTP/1.1" 200 40
[05/Apr/2023 13:37:42] "GET /polls/ HTTP/1.1" 200 40
[05/Apr/2023 13:37:44] "GET /polls/ HTTP/1.1" 200 40
[05/Apr/2023 13:37:45] "GET /polls/ HTTP/1.1" 200 40
[05/Apr/2023 13:37:46] "GET /polls/ HTTP/1.1" 200 40
[06/Apr/2023 03:39:02] "GET /polls/ HTTP/1.1" 200 40
[06/Apr/2023 03:42:15] "GET /polls/ HTTP/1.1" 200 40
[06/Apr/2023 04:08:31] "GET /polls HTTP/1.0" 301 0
[06/Apr/2023 04:08:31] "GET /polls/ HTTP/1.0" 200 40
/home/laish/mysite/mysite/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
April 05, 2023 - 13:16:19
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/laish/mysite/manage.py", line 22, in <module>
    main()
  File "/home/laish/mysite/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/conf/__init__.py", line 233, in __init__
    raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
ValueError: Incorrect timezone setting: UTC+8
Watching for file changes with StatReloader
[12/Apr/2023 13:06:39] "GET /polls HTTP/1.1" 301 0
[12/Apr/2023 13:07:04] "GET /polls HTTP/1.0" 301 0
[12/Apr/2023 13:07:04] "GET /polls/ HTTP/1.0" 200 40
/home/laish/mysite/mysite/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 12, 2023 - 13:06:10
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/apps/config.py", line 178, in create
    mod = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'polls.app'
/home/laish/mysite/mysite/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/laish/mysite/polls/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 12, 2023 - 19:38:57
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/home/laish/mysite/polls/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 12, 2023 - 19:46:43
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[18/Apr/2023 16:18:05] "GET /polls/ HTTP/1.0" 200 40
[18/Apr/2023 16:43:09] "GET /polls/ HTTP/1.0" 200 40
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[18/Apr/2023 16:57:02] "GET /polls/ HTTP/1.0" 200 40
Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Bad Request: /polls/
[18/Apr/2023 16:57:08] "GET /polls/ HTTP/1.1" 400 63382
Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[18/Apr/2023 16:57:10] "GET /favicon.ico HTTP/1.1" 400 63160
Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Bad Request: /
[18/Apr/2023 16:57:39] "GET / HTTP/1.1" 400 63096
Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '34.134.152.224:8000'. You may need to add '34.134.152.224' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[18/Apr/2023 16:57:41] "GET /favicon.ico HTTP/1.1" 400 63154
Watching for file changes with StatReloader
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Bad Request: /polls/
[18/Apr/2023 17:03:25] "GET /polls/ HTTP/1.0" 400 62577
[18/Apr/2023 17:03:35] "GET /polls/ HTTP/1.1" 200 40
Not Found: /favicon.ico
[18/Apr/2023 17:03:35] "GET /favicon.ico HTTP/1.1" 404 2221
[18/Apr/2023 17:03:42] "GET /polls/34 HTTP/1.1" 301 0
[18/Apr/2023 17:03:43] "GET /polls/34/ HTTP/1.1" 200 30
[18/Apr/2023 17:03:48] "GET /polls/34/ HTTP/1.1" 200 30
Not Found: /favicon.ico
[18/Apr/2023 17:03:49] "GET /favicon.ico HTTP/1.1" 404 2221
[18/Apr/2023 17:03:52] "GET /polls/34/ HTTP/1.1" 200 30
[18/Apr/2023 17:03:56] "GET /polls/34/ HTTP/1.1" 200 30
Not Found: /favicon.ico
[18/Apr/2023 17:03:56] "GET /favicon.ico HTTP/1.1" 404 2221
[18/Apr/2023 17:04:00] "GET /polls/34/ HTTP/1.1" 200 30
Not Found: /favicon.ico
[18/Apr/2023 17:04:00] "GET /favicon.ico HTTP/1.1" 404 2221
[18/Apr/2023 17:04:03] "GET /polls/34/ HTTP/1.1" 200 30
Not Found: /favicon.ico
[18/Apr/2023 17:04:04] "GET /favicon.ico HTTP/1.1" 404 2221
[18/Apr/2023 17:04:05] "GET /polls/34/ HTTP/1.1" 200 30
[18/Apr/2023 17:06:27] "GET /polls/ HTTP/1.1" 200 40
Not Found: /favicon.ico
[18/Apr/2023 17:06:30] "GET /favicon.ico HTTP/1.1" 404 2221
[18/Apr/2023 17:06:40,449] - Broken pipe from ('1.202.187.125', 11448)
[18/Apr/2023 17:06:40,449] - Broken pipe from ('1.202.187.125', 48587)
[18/Apr/2023 17:06:40,449] - Broken pipe from ('1.202.187.125', 42254)
[18/Apr/2023 17:17:15] "GET /polls/34/ HTTP/1.1" 200 30
[18/Apr/2023 18:14:13,506] - Broken pipe from ('167.94.146.59', 59024)
Not Found: /
[18/Apr/2023 18:14:14] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 18:14:14,753] - Broken pipe from ('167.94.146.59', 39592)
Not Found: /
[18/Apr/2023 18:14:14] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 18:14:15] code 505, message Invalid HTTP version (2.0)
[18/Apr/2023 18:14:15] "PRI * HTTP/2.0" 505 -
Not Found: /
[18/Apr/2023 18:28:22] "GET / HTTP/1.1" 404 2170
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
[18/Apr/2023 18:28:48] "GET http://api.ipify.org/?format=json HTTP/1.1" 400 62813
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
[18/Apr/2023 18:28:59] "CONNECT www.shadowserver.org:443 HTTP/1.1" 400 63016
[18/Apr/2023 18:52:36,192] - Broken pipe from ('162.142.125.217', 46166)
Not Found: /
[18/Apr/2023 18:52:37] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 18:52:37,216] - Broken pipe from ('162.142.125.217', 57816)
Not Found: /
[18/Apr/2023 18:52:37] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 18:52:37] code 505, message Invalid HTTP version (2.0)
[18/Apr/2023 18:52:37] "PRI * HTTP/2.0" 505 -
[18/Apr/2023 20:31:27,499] - Broken pipe from ('167.94.145.59', 55802)
Not Found: /
[18/Apr/2023 20:31:28] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 20:31:28,728] - Broken pipe from ('167.94.145.59', 36196)
Not Found: /
[18/Apr/2023 20:31:28] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 20:31:29] code 505, message Invalid HTTP version (2.0)
[18/Apr/2023 20:31:29] "PRI * HTTP/2.0" 505 -
[18/Apr/2023 22:45:32] code 400, message Bad request version ('À\x14À')
[18/Apr/2023 22:45:32] You're accessing the development server over HTTPS, but it only supports HTTP.
[18/Apr/2023 22:45:32] code 400, message Bad request version ('À\x14À')
[18/Apr/2023 22:45:32] You're accessing the development server over HTTPS, but it only supports HTTP.
Not Found: /
[18/Apr/2023 22:45:32] "GET / HTTP/1.1" 404 2170
[18/Apr/2023 22:45:32] code 400, message Bad request syntax ('\x16\x03\x01\x00{\x01\x00\x00w\x03\x03\x9e2Q\x14\x8f\x00[')
[18/Apr/2023 22:45:32] You're accessing the development server over HTTPS, but it only supports HTTP.
Not Found: /api/islogged
[18/Apr/2023 22:45:32] "GET /api/islogged HTTP/1.1" 404 2224
Not Found: /
[18/Apr/2023 23:42:09] "GET / HTTP/1.1" 404 2170
[19/Apr/2023 04:14:15] code 400, message Bad HTTP/0.9 request type ('Z¥\x01')
[19/Apr/2023 04:14:15] "Z¥     " 400 -
Not Found: /
[19/Apr/2023 04:18:20] "GET / HTTP/1.1" 404 2170
Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'api.ipify.org'. You may need to add 'api.ipify.org' to ALLOWED_HOSTS.
Bad Request: /http:/api.ipify.org/
[19/Apr/2023 04:18:56] "GET http://api.ipify.org/?format=json HTTP/1.1" 400 62777
Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/utils/deprecation.py", line 135, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "/home/laish/anaconda3/envs/djenv/lib/python3.11/site-packages/django/http/request.py", line 148, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'www.shadowserver.org'. You may need to add 'www.shadowserver.org' to ALLOWED_HOSTS.
Bad Request: /www.shadowserver.org:443
[19/Apr/2023 04:18:59] "CONNECT www.shadowserver.org:443 HTTP/1.1" 400 62980
Not Found: /
[19/Apr/2023 09:48:01] "GET / HTTP/1.1" 404 2170
Not Found: /
[19/Apr/2023 10:02:33] "GET / HTTP/1.1" 404 2170
Not Found: /
[19/Apr/2023 10:19:23] "GET / HTTP/1.1" 404 2170
Not Found: /favicon.ico
[19/Apr/2023 11:33:36] "GET /favicon.ico HTTP/1.1" 404 2221
Performing system checks...

System check identified no issues (0 silenced).
April 18, 2023 - 17:03:19
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Error: You don't have permission to access that port.
Watching for file changes with StatReloader
Error: You don't have permission to access that port.
Watching for file changes with StatReloader
Error: You don't have permission to access that port.
Watching for file changes with StatReloader
Error: You don't have permission to access that port.
Watching for file changes with StatReloader
[19/Apr/2023 12:15:48] "GET /polls/ HTTP/1.1" 200 40
Not Found: /favicon.ico
[19/Apr/2023 12:15:49] "GET /favicon.ico HTTP/1.1" 404 2221
[19/Apr/2023 12:15:55] "GET /admin HTTP/1.1" 301 0
[19/Apr/2023 12:15:55] "GET /admin/ HTTP/1.1" 302 0
[19/Apr/2023 12:15:56] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 2222
[19/Apr/2023 12:15:56] "GET /static/admin/css/base.css HTTP/1.1" 200 20344
[19/Apr/2023 12:15:56] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 796
[19/Apr/2023 12:15:56] "GET /static/admin/css/login.css HTTP/1.1" 200 958
[19/Apr/2023 12:15:56] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2619
[19/Apr/2023 12:15:56] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18854
[19/Apr/2023 12:15:56] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3763
[19/Apr/2023 12:15:57] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[19/Apr/2023 12:15:57] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[19/Apr/2023 12:15:58] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[19/Apr/2023 12:16:07] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[19/Apr/2023 12:16:07] "GET /admin/ HTTP/1.1" 200 4235
[19/Apr/2023 12:16:07] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[19/Apr/2023 12:16:07] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[19/Apr/2023 12:16:07] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
Not Found: /favicon.ico
[19/Apr/2023 12:16:07] "GET /favicon.ico HTTP/1.1" 404 2221
Not Found: /favicon.ico
[19/Apr/2023 12:16:08] "GET /favicon.ico HTTP/1.1" 404 2221
[19/Apr/2023 12:16:08] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[19/Apr/2023 12:16:15] "GET /admin/polls/question/ HTTP/1.1" 200 6560
[19/Apr/2023 12:16:15] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6395
[19/Apr/2023 12:16:15] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[19/Apr/2023 12:16:15] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[19/Apr/2023 12:16:15] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[19/Apr/2023 12:16:15] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8919
[19/Apr/2023 12:16:16] "GET /static/admin/js/actions.js HTTP/1.1" 200 7872
[19/Apr/2023 12:16:16] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[19/Apr/2023 12:16:16] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[19/Apr/2023 12:16:16] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
[19/Apr/2023 12:16:16] "GET /static/admin/js/filters.js HTTP/1.1" 200 966
[19/Apr/2023 12:16:16] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[19/Apr/2023 12:16:17] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[19/Apr/2023 12:16:18] "GET /admin/polls/question/1/change/ HTTP/1.1" 200 7128
[19/Apr/2023 12:16:19] "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[19/Apr/2023 12:16:19] "GET /static/admin/css/forms.css HTTP/1.1" 200 8944
[19/Apr/2023 12:16:19] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
[19/Apr/2023 12:16:19] "GET /admin/jsi18n/ HTTP/1.1" 200 3343
[19/Apr/2023 12:16:19] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[19/Apr/2023 12:16:19] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11297
[19/Apr/2023 12:16:19] "GET /static/admin/js/change_form.js HTTP/1.1" 200 1043
[19/Apr/2023 12:16:20] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[19/Apr/2023 12:16:20] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[19/Apr/2023 12:16:20] "GET /admin/polls/question/ HTTP/1.1" 200 6560
[19/Apr/2023 12:16:24] "GET /admin/ HTTP/1.1" 200 4235
Not Found: /
[19/Apr/2023 12:16:26] "GET / HTTP/1.1" 404 2170
/home/laish/mysite/mysite/settings.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
April 19, 2023 - 12:15:23
Django version 4.1, using settings 'mysite.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
